#!/bin/bash
#PBS -V
#PBS -N 4climake
#PBS -l walltime=00:50:00
#PBS -l mem=62GB
#PBS -l nodes=1:ppn=1
#PBS -A 2022_205


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#   Job #4
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

set -ex 

OUTPUTDIR=$1
CLIMAKEDIR=$2
CLIMAKEWORKDIR=$3
E923_UPDATE=$4

cd $OUTPUTDIR
echo '&namelist_vars
FNAME1="PGD.fa",
FNAME2="Const.Clim.01",
/' > fort.4

module purge
module swap cluster/dodrio/cpu_milan
module load iimpi/2022a imkl/2022.1.0 vsc-mympirun
module list
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/dodrio/scratch/projects/starting_2022_075/accord/software/iimpi2022a/lib64:/dodrio/scratch/projects/starting_2022_075/accord/software/iimpi2022a/auxlibs/lib
ulimit -s unlimited
ulimit -c unlimited

${CLIMAKEDIR}/scripts/replace_orography/replace_orography

rm fort.4

if [ "$E923_UPDATE" == "y" ]; then
cd $CLIMAKEWORKDIR/e923_update/script
ID=$(basename ${CLIMAKEWORKDIR})
./run.${ID}
fi

