#!/bin/bash
#PBS -V
#PBS -N 4climake
#PBS -l walltime=00:50:00
#PBS -l mem=62GB
#PBS -l nodes=1:ppn=1
#PBS -A 2022_205
#PBS -m a


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#   Job #4
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

set -ex 



cd $OUTPUTDIR
echo '&namelist_vars
FNAME1="PGD.fa",
FNAME2="Const.Clim.01",
/' > fort.4

module purge
# module swap cluster/dodrio/cpu_milan
# Change module to 2023 version
module load iimpi/2023a imkl/2023.1.0 vsc-mympirun
module list
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/dodrio/scratch/projects/2022_200/project_output/RMIB-UGent/vsc45302_kwinten/software/iimpi2023a/lib64 # Change this to correction location
ulimit -s unlimited
ulimit -c unlimited

${CLIMAKEDIR}/scripts/replace_orography/replace_orography

rm fort.4

if [ "$E923_UPDATE" == "y" ]; then
cd $CLIMAKEWORKDIR/e923_update/script
ID=$(basename ${CLIMAKEWORKDIR})
./run.${ID}
else
    # Remove work directory
    rm -rv $CLIMAKEWORKDIR
fi


