#!/bin/bash
CLIMAKE_VERSION=1.37
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#   
#   POSTPROMAKE MAIN JOB  #1
#  ('clone' of climake script aimed to produce postprocessing lat/lon grid clim files 
#   Calling step by step inside 'scripts' directory
#     1_fetch_files
#     2_make_pgd
#     3_job_923
#     4_finalize
#
#   Each one are 'self documented'
#   
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

set -e

Usage() {
echo "please use \"postpromake -c config_file\" (with config file mode)"
exit 1
}
if [ $# -eq 0 ]
then
	Usage
fi

CLIMAKEDIR=$PWD

if [ "$1" == "-c" ]; then
    echo "config file mode";
    CONFIGFILE=$2;

    if [ "$CONFIGFILE" == "" ]; then
	    echo "No config file provided, aborting...";
	    exit 1;
    fi
    if [ ! -f $2 ]; then
        echo "CONFIGFILE not found!";
        exit 1;

    else
        . $CONFIGFILE;
    fi
else
    Usage;
    exit 1;

fi

if [ -z $CYCLE ]; then
  echo "GENV Cycle must be passed by argument. Show README for more details. Aborting"
  exit 1
fi

if [ ! -f "$CLIMAKEDIR"/"$PGDGEO" ]; then
	echo 'PGD GEOMETRY file not found! This is mandatory in file mode'
	echo 'path given was '$PGDGEO
	echo 'Aborting'
	exit 1
fi
if [ ! -f "$CLIMAKEDIR"/"$CLIMGEO" ]; then
	echo '923 GEOMETRY file not found! This is mandatory in file mode'
	echo 'path given was '$CLIMGEO
	echo 'Aborting'
	exit 1
fi

#check if there is custom PGD or custom MASTER
if [[ -z "${CUSTOM_MASTER}" ]]; then
    CUSTOM_MASTER='GENERIC' 
else
   #test if it exists and if it is executable
   if [ ! -f $CUSTOM_MASTER ]; then
	  echo 'CUSTOM_MASTER environment variable is defined but the file is not there...'
	  echo 'was checking:'$CUSTOM_MASTER
      echo 'Aborting...'
      exit 1
   fi  
fi 
if [[ -z "${CUSTOM_PGD}" ]]; then
    CUSTOM_PGD='GENERIC' 
else
   #test if it exists and if it is executable
   if [ ! -f $CUSTOM_PGD ]; then
	  echo 'CUSTOM_PGD environment variable is defined but the file is not there...'
	  echo 'was checking:'$CUSTOM_PGD
      echo 'Aborting...'
      exit 1
   fi  
fi 
#---------------------------
#check if workdir is defined

CLIMAKEWORKDIR=$PWD/work_$CONFIGFILE

if [[ -z "${PGDHACK}" ]]; then
    PGDHACK=":" #nothing
# else
#     PGDHACK=$(realpath $PGDHACK)
fi


CLIMGEO=$(realpath $CLIMGEO)
PGDGEO=$(realpath $PGDGEO)
#clearing screen
clear

echo "-------*****-------" 
echo "WELCOME TO POSTPROMAKE, CLIMAKE VERSION :"$CLIMAKE_VERSION 
echo "-------*****-------" 

echo "You are in file mode: Epygram will NOT generate for you the geometry, you need to have provided valid files"
PGDGEOSHORT=(${PGDGEO//\// })
PGDGEOSHORT=${PGDGEOSHORT[@]: -1}
CLIMGEOSHORT=(${CLIMGEO//\// })
CLIMGEOSHORT=${CLIMGEOSHORT[@]: -1}

#ability to customize output dir
if [[ -z "${CUSTOM_OUT}" ]]; then
	OUTPUTDIR=$CLIMAKEDIR'/outputFiles/pgddomain-'$PGDGEOSHORT'__climdomain-'$CLIMGEOSHORT'__cycle-'$CYCLE'__v-'$CLIMAKE_VERSION
else
	OUTPUTDIR=$CLIMAKEDIR'/outputFiles/'${CUSTOM_OUT}
fi

E923_UPDATE="n"

echo '---------------------------'
echo '==========================='
echo '******LAUCHING POSTPROMAKE*****'
echo 'PGD GEOMETRY is '$PGDGEO
echo 'CLIM GEOMETRY is '$CLIMGEO
echo 'GENV CYCLE IS '$CYCLE
echo 'CLIMAKEDIR IS '$CLIMAKEDIR
echo 'OUTPUT DIR IS '$OUTPUTDIR
echo 'MASTER BINARY IS '$CUSTOM_MASTER
echo 'PGD BINARY IS '$CUSTOM_PGD
echo 'CLIMAKEWORKDIR IS '$CLIMAKEWORKDIR
echo 'PGDHACK IS '$PGDHACK
echo 'E923_UPDATE IS '$E923_UPDATE
echo 'DATA_DIR IS '$DATA_DIR
echo '==========================='
echo '---------------------------'

echo 'Do you confirm? (y/n)'
read answer
if [ "$answer" != "y" ];then
   echo 'Job canceled'
   exit 1
fi


[ ! -d $OUTPUTDIR'/listings' ] && mkdir -p $OUTPUTDIR'/listings'
[ ! -d $OUTPUTDIR'/log' ] && mkdir -p $OUTPUTDIR'/log'
cp -f $CONFIGFILE $OUTPUTDIR/.

# Create work directory
[ -d $CLIMAKEWORKDIR ] && rm -r $CLIMAKEWORKDIR
mkdir -p $CLIMAKEWORKDIR

# start job
qsub -o $OUTPUTDIR/log/1climake.o \
	 -e $OUTPUTDIR/log/1climake.e \
	 -v  PGDGEO=$PGDGEO,CLIMGEO=$CLIMGEO,CYCLE=$CYCLE,CLIMAKEDIR=$CLIMAKEDIR,OUTPUTDIR=$OUTPUTDIR,CUSTOM_MASTER=$CUSTOM_MASTER,CUSTOM_PGD=$CUSTOM_PGD,CLIMAKEWORKDIR=$CLIMAKEWORKDIR,E923_UPDATE=$E923_UPDATE,DATA_DIR=$DATA_DIR,PGDHACK=$PGDHACK \
	 scripts/1_postpro_makegeo
	 #sbatch --output=$OUTPUTDIR/log/1climake.o --error=$OUTPUTDIR/log/1climake.e scripts/1_fetch_files $PGDGEO $CLIMGEO $CYCLE $PGDNAM $CLIMNAM $OROGRAPHY_TRUNCATION $OTHERFIELDS_TRUNCATION $CLIMAKEDIR $OUTPUTDIR $CUSTOM_MASTER $CUSTOM_PGD $SPECTRALS_PARAMS $CLIMAKEWORKDIR $E923_UPDATE $DATA_DIR $PGDHACK
